apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tanks.neilprimmer.com
spec:
  group: neilprimmer.com
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                source:
                  type: object
                  description: "The source ConfigMap that acts as the configuration source-of-truth."
                  properties:
                    namespace:
                      type: string
                      description: "Namespace where the source ConfigMap resides."
                    name:
                      type: string
                      description: "Name of the source ConfigMap."
                  required:
                    - namespace
                    - name
                targetConfigMapName:
                  type: string
                  description: "The name of the ConfigMap that will be created or updated in each target namespace."
                  default: "tanked-config"
              required:
                - source
      subresources:
        status: {}
scope: Namespaced
names:
  plural: tanks
  singular: tank
  kind: Tank
  shortNames:
    - tank